[tool.poetry]
name = "python-opt"
version = "0.1.0"
description = ""
authors = ["hadacchi <master@hadacchi.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.2"
pytest = "^8.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
